name: travail_fute
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.1.1 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    intl: 0.19.0
    shared_preferences: ^2.5.1
    flutter_dotenv: ^5.0.2
    provider: ^6.0.5
    flutter_tts: ^3.2.2
    cupertino_icons: ^1.0.2
    flutter_native_splash: ^2.3.2
    phone_state: ^2.0.1
    permission_handler: ^11.3.1
    record: ^5.2.0
    path_provider: ^2.1.1
    audioplayers: ^6.1.0
    logger: ^2.0.2
    flutter_spinkit: ^5.2.0
    http: ^1.1.0
    flutter_form_builder: ^9.1.1

    path: any
    smswatcher: ^0.0.3
    flutter_sms_manager:
        path: ../flutter_sms_manager
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/splash.png
        - .env
        - assets/prompts/notification_prompt.txt

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
    color: "#FFFFFF"
    image: assets/images/splash.png
