name: travail_fute
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.1.1 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    intl: 0.19.0
    shared_preferences: ^2.5.1
    provider: ^6.0.5
    flutter_tts: ^3.2.2
    cupertino_icons: ^1.0.2
    flutter_native_splash: ^2.3.2
    phone_state: ^2.0.1
    permission_handler: ^11.3.1
    record: ^5.2.0
    path_provider: ^2.1.1
    audioplayers: ^6.1.0
    logger: ^2.0.2
    flutter_spinkit: ^5.2.0
    http: ^1.1.0
    flutter_form_builder: ^9.1.1
    flutter_local_notifications: ^18.0.1
    printing: ^5.12.0
    pdf: ^3.10.0
    speech_to_text: ^6.1.1
    path: any
    smooth_page_indicator: ^1.0.0
    flutter_datetime_picker_plus: ^2.2.0
    url_launcher: ^6.3.1
    flutter_launcher_icons: ^0.14.3
    image_picker: ^1.1.2
    cached_network_image: ^3.4.1
    syncfusion_flutter_pdfviewer: 28.2.9
    share_plus: ^10.1.4
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/app_logo.png
        - .env
        - assets/prompts/notification_prompt.txt

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    
flutter_native_splash:
    color: "#FFFFFF"
    image: assets/images/app_logo.png

    android_12:
        color: "#FFFFFF"
        image: assets/images/app_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"